# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8a67704484ecd25d5db71ad692c2d12b872171242dc678125c80a2323c258cdc88ec068e4b9adaac46e33fd69e351c7dea255713d5713c30efaee3a3fe79eb6

test:
  secret_key_base: 95d3e5d146589917a6744396dfb6fd582320bee82cbf1df8896c1b7dd924bba9d2df0172a6f431f3430ad866911d626033bed389c8b0b2f2f0d1ac9a536ea95b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
